# Generated by Django 5.2.3 on 2025-07-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default-user-icon.jpeg', null=True, upload_to='profiles/'),
        ),
    ]
