# Generated by Django 5.2.3 on 2025-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_twitter',
            new_name='social_telegram',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_x',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
