# Generated by Django 5.2.3 on 2025-06-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('Down Vote', 'Down'), ('Up Vote', 'Up')], max_length=200),
        ),
    ]
