# Generated by Django 5.2.3 on 2025-07-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
