# Generated by Django 5.2.3 on 2025-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploaded_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
